; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = lnpos

[env:esp32dev]
platform = espressif32@6.9.0 ; devo usare questa versione per evitare problemi con la libreria uBitcoin che non è compatibile con la versione 3 di arduino esp32
board = lilygo-t-display
framework = arduino
monitor_speed = 115200
lib_deps = 
    Keypad@^3.1.1
    ArduinoJson@^7.4.3
    Crypto@^0.4.0
    uBitcoin@^0.2.0
    QRCode@^0.0.1
    TFT_eSPI@^2.5.43
build_flags =
	-D TOUCH_PIN=T5 ; GPIO12
	-D BT1_PIN=35
    -D TFT
	-D USER_SETUP_LOADED=1
	-include $PROJECT_LIBDEPS_DIR/$PIOENV/TFT_eSPI/User_Setups/Setup25_TTGO_T_Display.h
	-D TOUCH_CS=-1